[tool.ruff]
line-length = 100
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "C90", # mccabe complexity
]
exclude = [
    ".venv",
    "venv",
    "__pycache__",
    "migrations",
]
ignore = [
    "E501",  # Ignore line length for now (can enable later)
] 