name: Frontend CI

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clear all caches
      run: |
        rm -rf ~/.npm
        rm -rf node_modules
        rm -rf frontend/node_modules
        rm -rf frontend/package-lock.json
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # Temporarily disable cache to force clean install
        # cache: 'npm'
        # cache-dependency-path: frontend/package-lock.json
        
    - name: Debug environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Working directory: $(pwd)"
        ls -la frontend/
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Check TypeScript types
      working-directory: ./frontend
      run: npm run type-check
      
    - name: Run Prettier check
      working-directory: ./frontend
      run: npm run format:check
      
    - name: Run ESLint
      working-directory: ./frontend
      run: npm run lint
      
    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false 