name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false
      
    - name: Run backend tests
      working-directory: ./backend
      run: pytest --cov=. --cov-report=xml
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Build Windows
      working-directory: ./frontend
      run: npm run electron:build:win
      
    - name: Build macOS
      working-directory: ./frontend
      run: npm run electron:build:mac
      
    - name: Build Linux
      working-directory: ./frontend
      run: npm run electron:build:linux
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          frontend/dist/*.exe
          frontend/dist/*.dmg
          frontend/dist/*.AppImage
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 